The advantages of support vector machines are:

1- Effective in high dimensional spaces.

2- Still effective in cases where number of dimensions is greater than the number of samples.

3- Uses a subset of training points in the decision function (called support vectors), so it is also memory efficient.

4-Versatile: different Kernel functions can be specified for the decision function. Common kernels are provided, but it is also possible to specify custom kernels.

In [1]:
from sklearn.svm import SVC
import numpy as np

In [2]:
X = np.array([[0, 0],[1,1]])
y = np.array([-1,1])

In [3]:
clf = SVC()

In [4]:
%%capture
clf.fit(X,y);

In [5]:
test=[-0.7, -1]
clf.predict([test])

array([-1])

In [6]:
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [7]:
 # get indices of support vectors
clf.support_

array([0, 1])

In [8]:
# get number of support vectors for each class
clf.n_support_ 

array([1, 1])