In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
xtrain = np.array([10,12,14,15,30,35,40,65]).reshape(-1,1)
xtrain

array([[10],
       [12],
       [14],
       [15],
       [30],
       [35],
       [40],
       [65]])

In [3]:
ytrain = (xtrain >20 )
ytrain

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True]])

In [4]:
model = linear_model.LogisticRegression(C=1000)      # regularization is applied by default

In [ ]:
#C : float, optional (default=1.0)
# Inverse of regularization strength; must be a positive float.
# smaller values specify stronger regularization.

In [5]:
model.fit(xtrain, ytrain)

C:\Users\Faradars-pc2\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Faradars-pc2\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [6]:
model.intercept_

array([-13.03530685])

In [7]:
model.coef_

array([[0.58438238]])

In [ ]:
#teta= [ intercept   coef  ]

In [9]:
### predict
xtest = np.array([8,13,32,36,65])

In [10]:
t = model.coef_ * xtest  + model.intercept_      #t = teta_t_x
t

array([[-8.36024781, -5.43833591,  5.66492932,  8.00245884, 24.94954787]])

In [11]:
ypred = 1 / (1 + np.exp(-t))
ypred = ypred.reshape(-1,1)
ypred

array([[2.33931606e-04],
       [4.32789847e-03],
       [9.96546575e-01],
       [9.99665473e-01],
       [1.00000000e+00]])