In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
x = np.array([1,2,3])   #  y = 2x+1
y = np.array([3,5,8])
plt.plot(x, y, "b.");

In [ ]:
X = np.c_[np.ones((3, 1)), x]          # add x0 = 1 to each instance
X

In [ ]:
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
theta

In [ ]:
xtest  = np.array([[0], [2],[4]])
xtest

In [ ]:
xtestb = np.c_[np.ones((3, 1)), xtest]  # add x0 = 1 to each instance
xtestb

In [ ]:
ypred = xtestb.dot(theta)
ypred

In [ ]:
plt.plot(xtest, ypred, "r-")
plt.plot(x, y, "b.");

In [ ]:
# sklearn

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([1,2,3]).reshape(-1,1)
x

array([[1],
       [2],
       [3]])

In [4]:
y = np.array([3,5,7]).reshape(-1,1)
y

array([[3],
       [5],
       [7]])

In [5]:
model = LinearRegression()

In [6]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
model.intercept_    #y=ax+b

array([1.])

In [8]:
model.coef_

array([[2.]])

In [9]:
xtest  = np.array([[0], [2],[4]]).reshape(-1,1)
xtest

array([[0],
       [2],
       [4]])

In [10]:
ypred = model.predict(xtest)
ypred

array([[1.],
       [5.],
       [9.]])